export type EquipoNCC = { name: string; members: string[] };

export const EQUIPOS_NCC_2026: EquipoNCC[] = [
  { name: "Nexus Consulting", members: ["Luna Brausin Correa", "Simon Eduardo Nieto Diaz", "Luisa María Arias Hernández", "María Teresa Pavajeau Ávila"] },
  { name: "ExcelEntes", members: ["Ana Sofía Merchán", "Susana Franco Cardozo", "Mateo Rincón"] },
  { name: "Golden Billow", members: ["Jose Melgarejo"] },
  { name: "SSAF: Strategic Solutions & Advisory Firm", members: ["Nelson Felipe Celis Díaz", "Sofia Morato Leyton", "Santiago Seade Rachadell", "Andrea Vargas Torres"] },
  { name: "Data solvers consulting", members: ["María Fernanda Muñoz Alfonso", "Franco Saavedra Camargo", "Lucas Valbuena Leon", "Juan Goyeneche Sáenz"] },
  { name: "Cordillera Partners", members: ["David Cabrera Trujillo", "Carlos Rodrigo Abondano", "Vanessa Alexandra Parra Paredes", "Angella Valeria Giambruno tarquino"] },
  { name: "Los Big 4", members: ["Mateo Gómez", "María José Sandoval", "Carlos Andrés Gómez", "Jung Hann Chu"] },
  { name: "A3E", members: ["Alejandro Jacob Florez Mayorga", "Andres Romero Reina", "Ellen Sofia Arevalo Ramos", "Ana Maria Rodriguez Caro"] },
  { name: "GAMMA Consulting", members: ["Manuela García", "Ana María Cuesta", "Gabriela Sandoval", "Alejandro Sánchez"] },
  { name: "Volt", members: ["Daniela Peñuela Bernal", "Sofia Vega Anillo"] },
  { name: "Javeriana FCB", members: ["José Manuel Chanchay Herrera", "Pablo Alejandro Valencia Baron"] },
  { name: "IMS Project", members: ["Manuela Siado Jaramillo", "Sofía Hernández Bustamante", "Isabella Muñoz Ramírez"] },
  { name: "NUEVO IMS", members: ["Sebastian Martinez Acevedo"] },
  { name: "Peak", members: ["Juan Pablo Ramirez", "Juan Sebastián Sterling", "Sebastián Rodríguez", "Juanita Cuervo"] },
  { name: "M3T Consulting", members: ["Nicolas Mendez", "Tomas Martinez", "Nicolas Moreno", "Simon toro"] },
  { name: "Monis Hunters", members: ["Juan Felipe Pulido Torres", "Juliana Gaviria Arroyave", "Santiago Rodriguez Vargas", "Samuel Iriarte Becerra"] },
  { name: "Impacta", members: ["Laura Isabella Casas Sierra", "Jose Daniel Aponte Pardo", "Maria Valeria Laverde Aponte", "Juan David Rico Espinosa"] },
  { name: "three makers", members: ["carla isabella sánchez rodríguez", "diego alejandro medina llanos", "pedro josé molina"] },
  { name: "NUEVA THREE MAKERS", members: ["Maria Jose Albarracin"] },
  { name: "STRATEX", members: ["Julián Esteban Mora Argote", "Zamir Esteban Torijano Saavedra", "Valeria Calderon Barreto", "Daniela Rivera Castillo"] },
  { name: "Convergence", members: ["Eduardo Alexander Gutiérrez Pérez", "Laura Alejandra Díaz Sastoque", "Santiago Mayorga Barriga", "Alejandra Millan Hinestrosa"] },
  { name: "Combo cadillo", members: ["Hower", "Martina Riaño Vergara", "Valerie Ortiz Román", "Laura Natalia Escamilla Chaparro"] },
  { name: "D-Krea", members: ["Dana Valentina Benavides Cruz", "Karol Juliana Hoyos Guerrero", "Daniela Gerardino Huertas", "Daniela Valentina López Ortíz"] },
  { name: "4ward Consulting", members: ["Juanita Valentina Cortés Vargas", "Pablo Novoa Cárdenas", "Ariadna Isabella Arcila Giraldo", "Andres Jaramillo Erazo"] },
  { name: "FM Consulting", members: ["Felipe Botero Godoy", "Mariana Moreno Sabogal", "Luis Felipe Cerón Salazar", "Marian Silvana Sierra Latorre"] },
  { name: "SODANAMA", members: ["NELSON DAVID RIOS MOLINA", "NATALIA VALENCIA", "Diana Sofia Vargas Montoya", "Mariana Duque Rodriguez"] },
  { name: "V4 Consulting", members: ["Valeria Buitrago Medina", "Maria Jose Saenz Carrizosa", "Gabriela Benedetti Leal", "Alejandra Franco Rivero"] },
  { name: "Nexus Strategy", members: ["Federico Barreto Barrero", "Nicolás Carrera More", "Nicholas Bautista Martínez", "Nicolas Suárez Burgos"] },
  { name: "Externomics", members: ["Ana Sofía Rodríguez Fonseca", "Isabella Vesga Luna", "Juan Miguel Riveros Galvis", "Thomas David Escobar Roa"] },
  { name: "Los Consultores", members: ["Daniel Benavides", "María José Serna", "Orlando Suárez", "Andrés Felipe Herrera"] },
  { name: "Northstar", members: ["María Paula Marín", "Camilo Garavito Barrios", "Maria Alejandra Sanabria Velandia", "Nicolás Manrique Ramirez"] },
  { name: "Total Consulting", members: ["María Corina Rengifo Romero", "Simón Cuello Iriarte", "Andrés Mauricio Rodríguez Ruiz", "María José Barraza Martínez"] },
  { name: "ALVIN Y LAS ARDILLAS", members: ["CARLOS DAVID SUAREZ MUÑOZ", "María Camila García", "Luisa Fernanda Fernández", "Mariana Gómez Sañudo"] },
  { name: "Equipo Omega", members: ["Dennys Alejandro Lozano Mora", "Nicolas Andrés Bolaños Fernandez", "Christian Alberto Bravo Montes", "Nicolás Fajardo Aguirre"] },
  { name: "THECNO", members: ["Diana Sofia Galvan Valbuena", "Dulce Mariana Torres Quiñones", "Andrea Johana Florez Bautista", "Eliana Higuera Guerrero"] },
  { name: "No Brainers", members: ["Manuel Felipe Guzmán Osorio", "Mateo Jaimes Rincon", "David Eduardo Cantor Baez", "Gabriela Campos Machado"] },
  { name: "Bull Partners", members: ["Juan Diego Moreno Miranda", "Salomon Gonzalez Lozada", "Miguelangel Villalba Moreno", "Efrain Santiago Tellez Becaria"] },
  { name: "Kairós", members: ["Rodrigo Paz Londoño", "Sara Valentina Rozo Oviedo", "Rosita Sofia Quintero Llorente", "Pablo Castellanos"] },
  { name: "Los Glegles", members: ["Samuel Rodríguez Peña", "Tomas Aponte", "Jairo David Acosta"] },
  { name: "MAJUR", members: ["Maria Juliana Romero Muñoz"] },
  { name: "Grupo PRISMA", members: ["David Felipe Rojas Gaitan", "Santiago Bernal Lugo", "Carol Sofía Cárdenas Osorio", "Simón Romero Gómez"] },
  { name: "Nova Pitch", members: ["Alejandra Duque Valencia", "Isabel Duque Londoño", "Daniela Gonzalez Ovalle", "Sofia Arias Zuluaga"] },
  { name: "Caso Cerrado", members: ["Laura Sofia Ayala Betancourt", "Carlos Alfredo Ayala Betancourt", "Sofía Acosta Muriel", "Alejandra Villarraga Rincon"] },
  { name: "Nexus", members: ["Julian Avendaño López", "Santiago Bravo Pinilla", "Jorge Luis Reyes Pasquale", "Nicolás Pinilla Suárez"] },
  { name: "Business Dream", members: ["Nahyelí Morón Hernández", "Sara Sofía Arevalo Rodríguez", "Ana Sofía Santander Prieto", "Laura Valentina Medina Acosta"] },
  { name: "Foursight Consulting Group", members: ["Isabella Santamaria Caballero", "Gabriela Bermudez Caicedo", "Isabela Garavito Ortiz", "Juliana Martines Marentes"] },
  { name: "Phronesis", members: ["Mariana Hernández", "Kendy Vanessa Fajardo", "Diego Alexandre Velez", "Ana María Beltrán", "Evasandryth Molina Arias"] },
  { name: "MonteCarlo", members: ["Juan Eduardo Ballesteros Pinzon", "Santiago Cordero Martinez", "Tomas Acosta Romero", "Maria Paula Peña Molina"] },
  { name: "Keystone", members: ["Camila Arias", "Gonzalo Grimaldos", "Manuela Romero", "Angelo di Marco"] },
  { name: "NUEVO ANGEL ICA", members: ["Julián Andrés Forero Salgado"] },
  { name: "Angel ICA Consultants", members: ["Oscar Santiago Narvaez Muñoz", "Nicolas Lopez Jimenez", "Diego Andres Montañes Capacho"] },
  { name: "Consultoti", members: ["EMILIO", "Juliana Salgar", "Sofia Angulo", "Martin Amaya"] },
  { name: "Los sinérgicos", members: ["Samuel Gualdrón Herrera", "Felipe Naranjo Vallejo", "Isabel Juliao Manotas"] },
  { name: "George David Muñoz", members: ["George David Muñoz Rodriguez"] },
  { name: "The Case Lab", members: ["Camila García Olarte", "Valentina Bohorquez", "Sofía Villamizar"] },
  { name: "Individual — Maria Jose Altamar Lozano", members: ["Maria Jose Altamar Lozano"] },
  { name: "JAMS Consulting", members: ["Mariana Hernandez Agudelo", "Simón Taylor Vásquez", "Daniela Alejandra Hernandez Ortiz", "Juan Esteban Oliveros Castillo"] },
  { name: "Consulting 360", members: ["Camila Uribe", "Juan Sebastian Rodriguez", "Abie Wiznitzer", "Isabella Suarez"] },
  { name: "The Estrategists", members: ["Valentina Torres Cárdenas", "Dana Sofía García", "Natalia López"] },
  { name: "Individual — Tere Eloisa Vanegas Perez", members: ["Tere Eloisa Vanegas Perez"] },
  { name: "NEXOR - Consulting", members: ["Edgar Saul Castillo Cueva", "Mauricio Alexander Garcia Camacho", "Andrés Gonzalo Luzuriaga Arévalo", "Galo Rafael Lomas Almeida"] },
  { name: "Code4andes", members: ["José Daniel Gómez cifuentes", "Kristin juliana canabal pájaro", "Samuel rojas duque", "Ricardo Alejandro Andrés suescun tapia"] },
  { name: "Ayllu", members: ["Emily Vianney Orbe Marcillo", "Andrea Verónica Muñoz Jiménez", "María Paula Pazmiño Toledo", "Josué Sebastián Cárdenas Jhayya"] },
  { name: "ETS & Co.", members: ["David \"El Tino (ET)\" Ramírez", "Esteban \"Sipilindo (S)\" Cacheo", "Zhanna Angeline \"& Co.\" Uscátegui Moreno", "Juan Diego \"& Co.\" Ortega Romero"] },
  { name: "Mêtis Consulting", members: ["Andrés Felipe Amador Henao", "Santiago Prada", "Daniel Galarza", "Alejandro Echeverría"] },
  { name: "Winners", members: ["Mariana Apráez", "Felipe Vargas", "Natalia Ayala", "Mariana Huertas"] },
  { name: "Gestión Elite", members: ["Domenica Saleth", "Gisel Priscila Imbacuán Reascos", "Lenin David Marcillo Fiallos", "Dayana Soledad Morales Simba"] },
  { name: "C4 Consulting Group", members: ["Jeronimo Londoño", "David Puerta Martínez CESA", "María Juliana Dussan Perdomo", "Tomas villaneda Forero"] },
  { name: "VENTUS", members: ["Laura Juanita Acosta Ríos", "Sofía Silva Escobar", "Natalia Paola Fuentes Ibáñez", "Sara Gabriela Janica Piñeros"] },
  { name: "FACEA UACH 1", members: ["Josefa Belén Aravena Carrasco", "Benjamín Herrera", "Maira Gallardo Burgos", "Antonia Andrade Barreaux"] },
  { name: "MJAI consulting", members: ["Antonia Marulanda  Montes", "Isabella Marin Perez", "Mariana De los angeles Páez Martínez", "Julieth Gomez Blanco"] },
  { name: "UACH FACEA 2", members: ["Ian Hoffmann", "Fernanda Montero Sanhueza", "Joseline Salgado Montero", "Nicole Gallardo"] },
  { name: "CESA CONS", members: ["Paloma Valencia", "Juan Felipe Pardo", "Zharick Orejuela Salazar", "Alejandro Gonzalez Serna"] },
  { name: "BOCAJRS", members: ["Tobias Meneghin"] },
  { name: "Los Pensadores", members: ["Luciano Eric Pinget", "Ian Luca Bonaldi"] },
  { name: "Individual — Julián Rodríguez", members: ["Julián Rodríguez"] },
  { name: "UNIVERSIDAD INDOAMERICA - EQUIPO 1", members: ["DAYANA MONSERRATH JIMENEZ", "JORGE ALEJANDRO VILLALVA NARANJO", "MATIAS SEBASTIAN VALENZUELA BARROS", "RANIA CAROLINA CAICEDO VILLACIS"] },
  { name: "Noesis Group", members: ["Karen Nicole Acevedo Mendez", "Karen Ximena Sepúlveda Bernal", "Nicolás López González", "Sebastian Santos Santos"] },
  { name: "UNIVERSIDAD INDOAMERICA - EQUIPO 2", members: ["ALISON SOLANGE PARADES CHASI", "EVELYN CAROLINA MORENO IZA", "ALISON SAMANTHA MEDINA ABRIL", "ESTEBAN MATEO AGUIERRE SANCHEZ"] },
  { name: "UNIVERSIDAD INDOAMERICA - EQUIPO 3", members: ["KERLY ANAHI JUNTA GAVILANES", "DANIELA MICHELLE VACA ALDAS", "LEANDRO SILVA CAMPOVERDE", "ANGEL DARIO VEINTIMILLA HERRERA"] },
  { name: "Strata", members: ["Maria Monica Rojas Trillos", "Juan David Guzman", "Catalina Maestre", "Alejandro Zambrano"] },
  { name: "Consultores Musicoadministradores", members: ["María Inés Díaz", "Ana María González", "Andrés Díaz", "Valeria Bulla"] },
  { name: "UR Monjes", members: ["Juan Esteban Triviño Betancourt", "Smaily Arenas", "David Rodriguez", "Jacobo Castaño"] },
  { name: "GILDCO", members: ["Pablo Apráez Abril", "Sebastián Barrera", "Santiago García de la Concha", "Leonardo Sánchez"] },
  { name: "IBBM Group", members: ["Ignacio Leiva Garrido", "Benjamín Cutiño Pacheco", "Benjamín Henríquez Torres", "Marcelo Vargas Troncoso"] },
  { name: "BCG (Barely Consulting Group)", members: ["Sofía Sanabria", "Andrés Herrera Muñoz", "Maya Misteli", "Santiago Rodriguez Llinas"] },
  { name: "SCG", members: ["Marie Elisa Aguilar", "Santiago Zambrano Iregui", "Cristian Felipe Forero Bejarano", "Manuela Rubio Barragán"] },
  { name: "Fourward", members: ["Sophia Bernal Trujillo", "Julian Gil Mejia", "Mateo Montes Montes", "Isabella Jiménez Macías"] },
  { name: "MRCR", members: ["Jacobo Rojas Uribe", "Sofía Carvajal Diaz", "Ana Sofía Miranda", "Laura Romero"] },
  { name: "Consultores Pro", members: ["Juan Esteban Salamanca", "Valentina Ramirez Pardo", "Jose Luis Meneses", "Iván Camilo Garcia"] },
  { name: "Praxis", members: ["Youichi David Tanaka Escobar", "Juan Luis Guevara Bustamante", "David Arce Rivera", "Camilo Andres Quiñonez"] },
  { name: "MV & TN", members: ["Tomas Lozano Sanint", "Nicolás Duarte Jaraba", "Mariana Gomez Vivas", "Valerie Ritzel"] },
  { name: "Procorp", members: ["Andrés Felipe Parra Alvarado", "Luz Madeleine Suárez Manzano", "Alejandro Pacheco Guerrero", "Mariana Valentina Ortega Aguilera"] },
  { name: "MindShift", members: ["David Alejandro Suárez Escorcia", "Daniela Hurtado Gutiérrez", "María Valentina Suárez Ayala", "Juan David Parra Tobías"] },
  { name: "Case Crackers 2.0", members: ["JOSE SEBASTIAN ZAMBRANO RUBI", "Ellin Jazmin Orjuela Santoyo", "Julián Steven Luna Romero", "Jerónimo Jiménez Castañeda"] },
  { name: "Los inges al cubo", members: ["Brian Nicolss Guzman Orjuela", "Lucía Anell", "Luz Enciso", "Joshua Miller"] },
  { name: "Nime consulting group", members: ["Mariana López Cobos", "Isabella Urdinola Hernandez", "Emilio Espinosa Palacio", "Nicolle Sanchez"] },
];
