/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EtapaGmatRouteImport } from './routes/etapa.gmat'
import { Route as EtapaStageRouteImport } from './routes/etapa.$stage'
import { Route as EtapaGmatQuizRouteImport } from './routes/etapa.gmat.quiz'
import { Route as ApiPublicGmatSubmitRouteImport } from './routes/api/public/gmat/submit'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EtapaGmatRoute = EtapaGmatRouteImport.update({
  id: '/etapa/gmat',
  path: '/etapa/gmat',
  getParentRoute: () => rootRouteImport,
} as any)
const EtapaStageRoute = EtapaStageRouteImport.update({
  id: '/etapa/$stage',
  path: '/etapa/$stage',
  getParentRoute: () => rootRouteImport,
} as any)
const EtapaGmatQuizRoute = EtapaGmatQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => EtapaGmatRoute,
} as any)
const ApiPublicGmatSubmitRoute = ApiPublicGmatSubmitRouteImport.update({
  id: '/api/public/gmat/submit',
  path: '/api/public/gmat/submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/etapa/$stage': typeof EtapaStageRoute
  '/etapa/gmat': typeof EtapaGmatRouteWithChildren
  '/etapa/gmat/quiz': typeof EtapaGmatQuizRoute
  '/api/public/gmat/submit': typeof ApiPublicGmatSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/etapa/$stage': typeof EtapaStageRoute
  '/etapa/gmat': typeof EtapaGmatRouteWithChildren
  '/etapa/gmat/quiz': typeof EtapaGmatQuizRoute
  '/api/public/gmat/submit': typeof ApiPublicGmatSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/etapa/$stage': typeof EtapaStageRoute
  '/etapa/gmat': typeof EtapaGmatRouteWithChildren
  '/etapa/gmat/quiz': typeof EtapaGmatQuizRoute
  '/api/public/gmat/submit': typeof ApiPublicGmatSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/etapa/$stage'
    | '/etapa/gmat'
    | '/etapa/gmat/quiz'
    | '/api/public/gmat/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/etapa/$stage'
    | '/etapa/gmat'
    | '/etapa/gmat/quiz'
    | '/api/public/gmat/submit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/etapa/$stage'
    | '/etapa/gmat'
    | '/etapa/gmat/quiz'
    | '/api/public/gmat/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EtapaStageRoute: typeof EtapaStageRoute
  EtapaGmatRoute: typeof EtapaGmatRouteWithChildren
  ApiPublicGmatSubmitRoute: typeof ApiPublicGmatSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etapa/gmat': {
      id: '/etapa/gmat'
      path: '/etapa/gmat'
      fullPath: '/etapa/gmat'
      preLoaderRoute: typeof EtapaGmatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etapa/$stage': {
      id: '/etapa/$stage'
      path: '/etapa/$stage'
      fullPath: '/etapa/$stage'
      preLoaderRoute: typeof EtapaStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etapa/gmat/quiz': {
      id: '/etapa/gmat/quiz'
      path: '/quiz'
      fullPath: '/etapa/gmat/quiz'
      preLoaderRoute: typeof EtapaGmatQuizRouteImport
      parentRoute: typeof EtapaGmatRoute
    }
    '/api/public/gmat/submit': {
      id: '/api/public/gmat/submit'
      path: '/api/public/gmat/submit'
      fullPath: '/api/public/gmat/submit'
      preLoaderRoute: typeof ApiPublicGmatSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EtapaGmatRouteChildren {
  EtapaGmatQuizRoute: typeof EtapaGmatQuizRoute
}

const EtapaGmatRouteChildren: EtapaGmatRouteChildren = {
  EtapaGmatQuizRoute: EtapaGmatQuizRoute,
}

const EtapaGmatRouteWithChildren = EtapaGmatRoute._addFileChildren(
  EtapaGmatRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EtapaStageRoute: EtapaStageRoute,
  EtapaGmatRoute: EtapaGmatRouteWithChildren,
  ApiPublicGmatSubmitRoute: ApiPublicGmatSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
